#!/usr/bin/env bash
for i in $* ; do
  url="$i"
  grep "^http"<<<"$url"
  if [ $? -ne 0 ] ; then
    url="http://www.youtube.com/watch?v=${url}"
  fi
  youtube-dl --restrict-filenames --audio-format=mp3 --extract-audio "${url}"
done
